---
version: "2.1"
services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/London
      - PASSWORD=AliAly032230
      - SUDO_PASSWORD=AliAly032230
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - /config:/config
      - /config/workspace:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
